version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8080:8080"

  # kafka-connect:
  #   image: confluentinc/cp-kafka-connect:latest
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8083:8083"

  kafka-connect-mongo:
    image: johnnyip/cloud-kafka-connect-mongodb:latest
    depends_on:
      - kafka
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017

  crawler:
    image: johnnyip/cloud-crawler
    environment:
      - KAFKA_URL=kafka:9092
    depends_on:
      - kafka

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
    environment:
      - WATCHTOWER_CLEANUP=true
