---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      restartPolicy: Always
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      restartPolicy: Always
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
          value: "true"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.kafka.svc.cluster.local:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      restartPolicy: Always
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: kafka.kafka.svc.cluster.local:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-mongo
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-mongo
  template:
    metadata:
      labels:
        app: kafka-connect-mongo
    spec:
      restartPolicy: Always
      containers:
        - name: kafka-connect-mongo
          image: johnnyip/cloud-kafka-connect-mongodb
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb.kafka.svc.cluster.local:27017"
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "kafka-connect-mongo.kafka.svc.cluster.local"
            - name: CONNECT_REST_ADVERTISED_PORT
              value: "8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb
          image: mongo:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      restartPolicy: Always
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://mongodb.kafka.svc.cluster.local:27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      restartPolicy: Always
      containers:
        - name: crawler
          image: johnnyip/cloud-crawler
          env:
            - name: KAFKA_URL
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: MONGODB_URL
              value: "mongodb://mongodb.kafka.svc.cluster.local:27017"


---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
  - port: 2181
    name: zk-port
  type: LoadBalancer
  selector:
    app: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
  type: LoadBalancer
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  ports:
  - port: 8080
    name: kafka-ui-port
  type: LoadBalancer
  selector:
    app: kafka-ui
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-mongo
  namespace: kafka
spec:
  ports:
  - port: 8083
    name: kafka-connect-mongo
  type: LoadBalancer
  selector:
    app: kafka-connect-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: kafka
spec:
  ports:
  - port: 27017
    name: mongodb
  type: LoadBalancer
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: kafka
spec:
  ports:
  - port: 8081
    name: mongo-express
  type: LoadBalancer
  selector:
    app: mongo-express
